apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rcs-network-policy
  namespace: rcs
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rcs
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    - to:
        - ipBlock:
            cidr: 34.8.247.114/32
      ports:
        - protocol: TCP
          port: 443
